# Generated by Django 2.2.6 on 2019-10-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='bio',
            field=models.TextField(default='I am a baker'),
            preserve_default=False,
        ),
    ]
