# Generated by Django 2.2.6 on 2019-10-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box', '0002_chef_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_required',
            field=models.TextField(default='About 60 min'),
            preserve_default=False,
        ),
    ]
