# Generated by Django 2.2.6 on 2019-10-31 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box', '0003_recipe_time_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
