# Generated by Django 2.2.6 on 2019-11-01 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box', '0004_auto_20191031_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 1, 13, 11, 59, 663639, tzinfo=utc)),
        ),
    ]
