# Generated by Django 2.2.6 on 2019-11-01 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box', '0005_auto_20191101_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
