# Generated by Django 2.2.6 on 2019-11-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box', '0006_auto_20191101_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_required',
            field=models.CharField(max_length=50),
        ),
    ]
